spring:
  application:
    name: Caip-BackEnd
  profiles:
    active: ${PROFILE_ACTIVE:dev}

  servlet:
    multipart:

      max-file-size: 10MB
      max-request-size: 12MB


server:
  # Porta padrão da aplicação, independentemente do ambiente.
  port: 8080

# ===================================================================
# CONFIGURAÇÕES DA APLICAÇÃO (Customizadas)
# ===================================================================
cors:
  allowed-origins: "http://localhost:5173,http://localhost:4173,http://localhost:5174"
# Configurações do Swagger (Springdoc)
springdoc:

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter:
    deep-linking: true
    show-actuator: false
  api-docs:
    enabled: true
    path: /v3/api-docs

swagger-info:
  ambient: ${PROFILE_ACTIVE:Desenvolvimento Local}

# ===================================================================
# OBSERVABILIDADE (Logs e Métricas)
# ===================================================================
logging:
  pattern:
    # Formato de log clássico do Spring Boot, com cores organizadas para fácil leitura.
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n"
  level:
    root: INFO

    org.marllon.caip: DEBUG

    org.springframework.security: DEBUG


management:
  endpoints:
    web:
      exposure:

        include: health,info,metrics
  endpoint:
    health:

      show-details: when_authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# ===================================================================
# BUCKET4J (Rate Limiting) - O Segurança
# ===================================================================
bucket4j:
  enabled: true
  # Configurações do Redis que ele deve procurar a conexão JCache (que amarramos ao Redisson)
  cache-to-use: jcache
  filters:
    - cache-name: rate-limit-login
      url: /auth/login.*
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"Muitas tentativas. Aguarde 15 minutos.\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 5
              time: 15
              unit: minutes